name: Basic CI Test

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Test AWS Connection
        run: |
          echo "Testing AWS connection..."
          aws sts get-caller-identity
          echo "AWS connection successful!"

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t vehicle-insurance:test .
          echo "Docker build successful!"
